import React from "react";
import {
  Accordion,
  AccordionPanel,
  Anchor,
  Box,
  Button,
  Card,
  CardHeader,
  CardBody,
  Header,
  Heading,
  Image,
  Paragraph,
  Page,
  PageContent,
  Tag,
  Text,
} from "grommet";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <Box width="100%">
      <Text>Tagline</Text>
      <Heading level={2}>About</Heading>
      <Paragraph></Paragraph>
      {/* <Heading level={2}>Skills</Heading> */}
      {/* <Heading level={3}>Development</Heading>
      <Tag name="React" />
      <Tag name="JavaScript" />
      <Tag name="TypeScript" />
      <Tag name="HTML" />
      <Tag name="CSS" />
      <Tag name="C++" />
      <Tag name="Java" />
      <Heading level={3}>Other</Heading>
      <Tag name="Accessibility" />
      <Tag name="GitHub" />
      <Tag name="JAWS" />
      <Tag name="Open Source" />
      <Tag name="TestCafe" />
      <Tag name="Jest" /> */}
      <Heading level={2}>Projects</Heading>
      <Box
        // direction="row-responsive"
        // justify="stretch"
        // alignSelf="center"
        // alignContent="center"
        // wrap
        fill="horizontal"
        width="100%"
        gap="medium"
      >
        <Box
          round="large"
          pad="medium"
          background="#ffffff15"
          //   height={{ max: "medium", min: "xsmall" }}
          //   width={{ max: "medium", min: "xsmall" }}
          //   width="100%"
          fill="horizontal"
          //   height="medium"
          direction="row-responsive"
          gap="medium"
        >
          <Box round="medium" width="medium" overflow="hidden">
            <Image width="100%" fit="cover" src="RayTracer_0.png" />
          </Box>
          <Box fill="horizontal" flex>
            <Heading level={3} margin="none">
              Ray Tracer
            </Heading>
            <Paragraph>
              A C++ application that generates images based on customizable
              driver flies.
            </Paragraph>
            <Box>
              <Button color="pink" primary onClick={() => {}}>
                Learn more
              </Button>
            </Box>
          </Box>
        </Box>
        <Box
          round="large"
          pad="medium"
          background="#ffffff15"
          //   height={{ max: "medium", min: "xsmall" }}
          width={{ max: "medium", min: "xsmall" }}
          height="medium"
        >
          <Box round="medium" fill overflow="hidden">
            <Image width="100%" fit="cover" src="Grommet_graphic_1.png" />
          </Box>
        </Box>
        <Box
          round="large"
          pad="medium"
          background="#ffffff15"
          //   height={{ max: "medium", min: "xsmall" }}
          width={{ max: "medium", min: "xsmall" }}
          height="medium"
          // width="m"
        >
          <Box round="medium" fill overflow="hidden">
            <Image width="100%" fit="cover" src="DS_graphic_1.png" />
          </Box>
        </Box>
      </Box>

      {/* <Box gap="medium" justify="evenly" direction="row-responsive">
        <Card height="250px" width={{ min: "small", max: "medium" }}>
          <Link to="/raytracer">
            <CardHeader>Ray Tracer</CardHeader>
            <CardBody fill>
              <Image
                fit="cover"
                src="RayTracer_0.png"
                a11yTitle="An image generated by a RayTracer program showing a series of spheres in a helix pattern reflecting off of each other."
              />
            </CardBody>
          </Link>
        </Card>
        <Card height="250px" width={{ min: "small", max: "medium" }}>
          <CardHeader>Project 2</CardHeader>
          <CardBody>
            <Image
              fit="cover"
              src="DS_graphic_1.png"
              a11yTitle="An image generated by a RayTracer program showing a series of spheres in a helix pattern reflecting off of each other."
            />
          </CardBody>
        </Card>
        <Card height="250px" width={{ min: "small", max: "medium" }}>
          <CardHeader>Project 3</CardHeader>
          <CardBody>
            <Image
            //   width="100%"
              fit="cover"
              src="Grommet_graphic_1.png"
              a11yTitle="An image generated by a RayTracer program showing a series of spheres in a helix pattern reflecting off of each other."
            />
          </CardBody>
        </Card>
      </Box> */}
      {/* <Heading level={2}>Professional Experience</Heading>
      <Accordion>
        <AccordionPanel label="job 1">Text</AccordionPanel>
        <AccordionPanel label="job 2">Text</AccordionPanel>
      </Accordion> */}
      <Heading level={2}>Contact</Heading>
      <Anchor href="#" label="linkedin" />
      <Anchor href="#" label="github" />
    </Box>
  );
};

export default Home;
