import React from "react";
import {
  Accordion,
  AccordionPanel,
  Anchor,
  Card,
  CardHeader,
  CardBody,
  Grommet,
  Header,
  Heading,
  Image,
  Paragraph,
  Page,
  PageContent,
  Tag,
  Text,
} from "grommet";
import { theme } from "./theme";

const App = () => {
  return (
    <Grommet theme={theme}>
      <Page kind="narrow" background={theme.global.colors.cream}>
        <PageContent>
          <Header alignSelf="center">
            <Heading>Jessica Filben</Heading>
          </Header>
          <hr />
          <Text>Tagline</Text>
          <Heading level={2}>About</Heading>
          <Paragraph>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </Paragraph>
          <Heading level={2}>Skills</Heading>
          <Heading level={3}>Development</Heading>
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Heading level={3}>Other</Heading>
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Tag name="tag" />
          <Heading level={2}>Projects</Heading>
          <Card height="medium">
            <CardHeader>Ray Tracer</CardHeader>
            <CardBody>
              <Image
                src="/RayTracer_1.png"
                a11yTitle="An image generated by a RayTracer program showing a series of spheres in a helix pattern reflecting off of each other."
              />
            </CardBody>
          </Card>
          <Card height="medium">
            <CardHeader>Project 2</CardHeader>
            <CardBody>img description</CardBody>
          </Card>
          <Card height="medium">
            <CardHeader>Project 3</CardHeader>
            <CardBody>img description</CardBody>
          </Card>
          <Card height="medium">
            <CardHeader>Project 4</CardHeader>
            <CardBody>img description</CardBody>
          </Card>
          <Heading level={2}>Professional Experience</Heading>
          <Accordion>
            <AccordionPanel label="job 1">Text</AccordionPanel>
            <AccordionPanel label="job 2">Text</AccordionPanel>
          </Accordion>
          <Heading level={2}>Contact</Heading>
          <Anchor href="#" label="linkedin" />
          <Anchor href="#" label="github" />
        </PageContent>
      </Page>
    </Grommet>
  );
};

export default App;
